const images = [
  { url: "/images/pixelart/harrings.png", text: "our staircase burns in the fog of our dreams, thy distant memory of movement" },
    { url: "/images/pixelart/sheer.png", text: "" },
  { url: "/images/pixelart/vines.png", text: "" },
  { url: "/images/pixelart/shackle.png", text: "ruins in the fortress,\*blinds in the nothing" },
  { url: "/images/pixelart/convent.png", text: "" },
  { url: "/images/pixelart/mothering.png", text: "" },
  { url: "/images/pixelart/asfjhf.png", text: "" },
  { url: "/images/pixelart/ae.png", text: "" },
  { url: "/images/pixelart/lovers_fate.png", text: "" },
  { url: "/images/pixelart/mwihihi.png", text: "" },
  { url: "/images/pixelart/steam.png", text: "" },
  { url: "/images/pixelart/free.png", text: "" },
  { url: "/images/pixelart/gear.png", text: "" },
  { url: "/images/pixelart/mine.png", text: "" },
  { url: "/images/pixelart/chain.png", text: "" },
  { url: "/images/pixelart/rpo.png", text: "" },
  { url: "/images/pixelart/mothering.png", text: "" },
  { url: "/images/pixelart/gasp.png", text: "" },
  { url: "/images/pixelart/court.png", text: "" },
  { url: "/images/pixelart/chant_more.png", text: "" },
  { url: "/images/pixelart/acustody.gif", text: "" },
  { url: "/images/pixelart/SURFACE22.png", text: "" },
  { url: "/images/pixelart/harsh.png", text: "" },
  { url: "/images/pixelart/yeanrning.png", text: "" },
  { url: "/images/pixelart/reaper.png", text: "" },
  { url: "/images/pixelart/burning.png", text: "" },
  { url: "/images/pixelart/start.png", text: "" },
  { url: "/images/pixelart/hrth.png", text: "" },
  { url: "/images/pixelart/qsdsd.png", text: "" },
  { url: "/images/pixelart/scared.png", text: "" },
  { url: "/images/pixelart/theory_.png", text: "" },
  { url: "/images/pixelart/asfjhf.png", text: "" },
  { url: "/images/pixelart/torture.png", text: "" },
  { url: "/images/pixelart/TORMENT3.png", text: "" },
  { url: "/images/pixelart/fuse.gif", text: "" },
  { url: "/images/pixelart/wilderness.gif", text: "" },
  { url: "/images/pixelart/sorched_white.png", text: "" },
  { url: "/images/pixelart/foe2.png", text: "" },
  { url: "/images/pixelart/tormenting.gif", text: "" },
  { url: "/images/pixelart/white.png", text: "" },
  { url: "/images/pixelart/warp.png", text: "" },
  { url: "/images/pixelart/and_the_role.png", text: "" },
  { url: "/images/pixelart/darker_.png", text: "" },
  { url: "/images/pixelart/side.png", text: "" },
  { url: "/images/pixelart/eternal_pastel_3.gif", text: "" },
  { url: "/images/pixelart/breathingg.gif", text: "" },
  { url: "/images/pixelart/north.png", text: "" },
  { url: "/images/pixelart/crow.png", text: "" },
  { url: "/images/pixelart/prisoner.png", text: "" },
  { url: "/images/pixelart/molded.png", text: "" },
  { url: "/images/pixelart/shed.png", text: "" },
  { url: "/images/pixelart/choicess.png", text: "" },
  { url: "/images/pixelart/choice_red.png", text: "" },
  { url: "/images/pixelart/pained.png", text: "" },
  { url: "/images/pixelart/beg.png", text: "" },
  { url: "/images/pixelart/crave.png", text: "" },
  { url: "/images/pixelart/lost.png", text: "" },
  { url: "/images/pixelart/bleh.png", text: "" },
  { url: "/images/pixelart/dust.png", text: "" },
  { url: "/images/pixelart/burnin.png", text: "" },
  { url: "/images/pixelart/headless_red.png", text: "" },
  { url: "/images/pixelart/wind.png", text: "" },
  { url: "/images/pixelart/loss_leader.png", text: "" },
  { url: "/images/pixelart/masteras.png", text: "" },
  { url: "/images/pixelart/sand_.png", text: "" },
  { url: "/images/pixelart/vent.png", text: "" },
  { url: "/images/pixelart/room.png", text: "" },
  { url: "/images/pixelart/broth.png", text: "" },
  { url: "/images/pixelart/maps.png", text: "" },
  { url: "/images/pixelart/rotten.png", text: "" },
  { url: "/images/pixelart/web.png", text: "" },
  { url: "/images/pixelart/screech.png", text: "" },
  { url: "/images/pixelart/scar.png", text: "" },
  { url: "/images/pixelart/croack2.png", text: "" },
  { url: "/images/pixelart/strangle_2.png", text: "" },
  { url: "/images/pixelart/stae.png", text: "" },
  { url: "/images/pixelart/vile.png", text: "" },
  { url: "/images/pixelart/cathedral_.png", text: "" },
  { url: "/images/pixelart/steel.png", text: "" },
  { url: "/images/pixelart/crossed.png", text: "" },
  { url: "/images/pixelart/athen.png", text: "" },
  { url: "/images/pixelart/saturn.png", text: "" },
  { url: "/images/pixelart/sheet.png", text: "" },
  { url: "/images/pixelart/thaid.png", text: "" },
  { url: "/images/pixelart/blow.png", text: "" },
  { url: "/images/pixelart/theft.png", text: "" },
  { url: "/images/pixelart/thaerr.png", text: "" },
  { url: "/images/pixelart/wisp.png", text: "" },
  { url: "/images/pixelart/Untitled-2.gif", text: "" },
  { url: "/images/pixelart/b.png", text: "" },
  { url: "/images/pixelart/loan.png", text: "" },
  { url: "/images/pixelart/pale_phantom_.png", text: "" },
  { url: "/images/pixelart/wear_off.png", text: "" },
  { url: "/images/pixelart/maiden.png", text: "" },
  { url: "/images/pixelart/brother.png", text: "" },
  { url: "/images/pixelart/white_mountain.png", text: "" },
  { url: "/images/pixelart/toad.png", text: "" },
  { url: "/images/pixelart/achiever.png", text: "" },
  { url: "/images/pixelart/cryptid.png", text: "" },
  { url: "/images/pixelart/wailing.png", text: "" },
  { url: "/images/pixelart/mbnm.png", text: "" },
  { url: "/images/pixelart/xsvsd.png", text: "" },
  { url: "/images/pixelart/dream.png", text: "" },
  { url: "/images/pixelart/dfgmn.png", text: "" },
  { url: "/images/pixelart/giant.png", text: "" },
  { url: "/images/pixelart/ket.png", text: "" },
  { url: "/images/pixelart/man.png", text: "" },
  { url: "/images/pixelart/moth.png", text: "" },
  { url: "/images/pixelart/ploy.png", text: "" },
  { url: "/images/pixelart/savior.png", text: "" },
  { url: "/images/pixelart/swword.png", text: "" },
  { url: "/images/pixelart/tower.png", text: "" },
  { url: "/images/pixelart/mistress.png", text: "" },
  { url: "/images/pixelart/hostile.png", text: "" },
  { url: "/images/pixelart/shock.png", text: "" },
  { url: "/images/pixelart/lost2.png", text: "" },
  { url: "/images/pixelart/feather.png", text: "" },
  { url: "/images/pixelart/engine.png", text: "" },
  { url: "/images/pixelart/ruin2.png", text: "" },
  { url: "/images/pixelart/whole.png", text: "" },
  { url: "/images/pixelart/wings.png", text: "" },
  { url: "/images/pixelart/glore.png", text: "" },
  { url: "/images/pixelart/gleam.png", text: "" },
  { url: "/images/pixelart/disaster.png", text: "" },
  { url: "/images/pixelart/handle.png", text: "" },
  { url: "/images/pixelart/cope.png", text: "" },
  { url: "/images/pixelart/caped_2.png", text: "" },
  { url: "/images/pixelart/flesh_.gif", text: "" },
  { url: "/images/pixelart/oath_red.png", text: "" },
  { url: "/images/pixelart/slither.gif", text: "" },
  { url: "/images/pixelart/reign.gif", text: "" },
  { url: "/images/pixelart/vanished_.gif", text: "" },
  { url: "/images/pixelart/surface.gif", text: "" },
  { url: "/images/pixelart/third_red.png", text: "" },
  { url: "/images/pixelart/chaos.png", text: "" },
  { url: "/images/pixelart/scream.png", text: "" },
  { url: "/images/pixelart/thylord!.png", text: "" },
  { url: "/images/pixelart/fate.png", text: "" },
  { url: "/images/pixelart/fool.png", text: "" },
  { url: "/images/pixelart/ages.png", text: "" },
  { url: "/images/pixelart/lock2.png", text: "" },
  { url: "/images/pixelart/sight4.png", text: "" },
  { url: "/images/pixelart/sighted2.png", text: "" },
  { url: "/images/pixelart/trin.png", text: "" },
  { url: "/images/pixelart/morbid.png", text: "" },
  { url: "/images/pixelart/feral.png", text: "" },
  { url: "/images/pixelart/arch.png", text: "" },
  { url: "/images/pixelart/failure.png", text: "" },
  { url: "/images/pixelart/corpse.png", text: "" },
  { url: "/images/pixelart/wizard.png", text: "" },
  { url: "/images/pixelart/for.png", text: "" },
  { url: "/images/pixelart/golem2.png", text: "" },
  { url: "/images/pixelart/hunters.png", text: "" },
  { url: "/images/pixelart/ruins.png", text: "" },
  { url: "/images/pixelart/cog.png", text: "" },
  { url: "/images/pixelart/fain.png", text: "" },
  { url: "/images/pixelart/veils.png", text: "" },
  { url: "/images/pixelart/scorned.png", text: "" },
  { url: "/images/pixelart/plague.png", text: "" },
  { url: "/images/pixelart/jar.png", text: "" },
  { url: "/images/pixelart/summon.png", text: "" },
  { url: "/images/pixelart/black_sun_.png", text: "" },
  { url: "/images/pixelart/stain_.png", text: "" },
  { url: "/images/pixelart/scare.gif", text: "" },
  { url: "/images/pixelart/asdasd.png", text: "" },
  { url: "/images/pixelart/dfgdfg.png", text: "" },
  { url: "/images/pixelart/solder.png", text: "" },
  { url: "/images/pixelart/serpents.png", text: "" },
  { url: "/images/pixelart/the%20flame.png", text: "" },
  { url: "/images/pixelart/boar.png", text: "" },
  { url: "/images/pixelart/mech.png", text: "" },
  { url: "/images/pixelart/stranger.png", text: "" },
  { url: "/images/pixelart/shill.png", text: "" },
  { url: "/images/pixelart/black.png", text: "" },
  { url: "/images/pixelart/forth.png", text: "" },
  { url: "/images/pixelart/hills.png", text: "" },
  { url: "/images/pixelart/flood.png", text: "" },
  { url: "/images/pixelart/wish_.png", text: "" },
  { url: "/images/pixelart/ambiguous_.png", text: "" },
  { url: "/images/pixelart/anchor_.png", text: "" },
  { url: "/images/pixelart/peasant.png", text: "" },
  { url: "/images/pixelart/credi_t.png", text: "" },
  { url: "/images/pixelart/path.png", text: "" },
  { url: "/images/pixelart/xsvsd.png", text: "" }
  // Add more image URLs and associated text as needed
];

let currentIndex = 0;

const imageElement = document.getElementById("galleryImage");
const textElement = document.getElementById("imageText");
const nextButton = document.getElementById("nextButton");
const backButton = document.getElementById("backButton");

function showCurrentImage() {
  const currentImage = images[currentIndex];
  imageElement.src = currentImage.url;
  textElement.innerHTML = currentImage.text.replace(/\*/g, "<br>");
}

function showNextImage() {
  currentIndex = (currentIndex + 1) % images.length;
  showCurrentImage();
}

function showPreviousImage() {
  currentIndex = (currentIndex - 1 + images.length) % images.length;
  showCurrentImage();
}

nextButton.addEventListener("click", showNextImage);
backButton.addEventListener("click", showPreviousImage);

showCurrentImage();